spring.application.name=shortlisting-service
spring.devtools.restart.enabled=true


spring.datasource.url=jdbc:postgresql://localhost:7001/shortlisting
spring.datasource.username=shortlisting
spring.datasource.password=shortlisting
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.azure.openai.endpoint=""
spring.ai.azure.openai.api-key=""
spring.ai.azure.openai.embedding.options.deployment-name=""